2018-01-21 08:16:04,255 ERROR 8460 [-/::1/-/74ms POST /login] nodejs.ReferenceError: debug is not defined
    at Strategy.app.passport.use.LocalStrategy [as _verify] (D:\JS\passport\app.js:15:5)
    at Strategy.authenticate (D:\JS\passport\node_modules\passport-local\lib\strategy.js:88:12)
    at attempt (D:\JS\passport\node_modules\passport\lib\middleware\authenticate.js:348:16)
    at authenticate (D:\JS\passport\node_modules\passport\lib\middleware\authenticate.js:349:7)
    at Promise (D:\JS\passport\node_modules\egg-passport\lib\framework.js:83:7)
    at new Promise (<anonymous>)
    at Object.passportAuthenticate (D:\JS\passport\node_modules\egg-passport\lib\framework.js:77:15)
    at passportAuthenticate.next (<anonymous>)
    at Object.dispatch (D:\JS\passport\node_modules\koa-router\lib\router.js:334:5)
    at dispatch.next (<anonymous>)
    at onFulfilled (D:\JS\passport\node_modules\co\index.js:65:19)
    at D:\JS\passport\node_modules\co\index.js:54:5
    at new Promise (<anonymous>)
    at Object.co (D:\JS\passport\node_modules\co\index.js:50:10)
    at Object.toPromise (D:\JS\passport\node_modules\co\index.js:118:63)
    at next (D:\JS\passport\node_modules\co\index.js:99:29)

pid: 8460
hostname: ghm-pc

2018-01-21 08:16:48,796 ERROR 8460 [-/::1/-/3ms POST /login] nodejs.ReferenceError: debug is not defined
    at Strategy.app.passport.use.LocalStrategy [as _verify] (D:\JS\passport\app.js:15:5)
    at Strategy.authenticate (D:\JS\passport\node_modules\passport-local\lib\strategy.js:88:12)
    at attempt (D:\JS\passport\node_modules\passport\lib\middleware\authenticate.js:348:16)
    at authenticate (D:\JS\passport\node_modules\passport\lib\middleware\authenticate.js:349:7)
    at Promise (D:\JS\passport\node_modules\egg-passport\lib\framework.js:83:7)
    at new Promise (<anonymous>)
    at Object.passportAuthenticate (D:\JS\passport\node_modules\egg-passport\lib\framework.js:77:15)
    at passportAuthenticate.next (<anonymous>)
    at Object.dispatch (D:\JS\passport\node_modules\koa-router\lib\router.js:334:5)
    at dispatch.next (<anonymous>)
    at onFulfilled (D:\JS\passport\node_modules\co\index.js:65:19)
    at D:\JS\passport\node_modules\co\index.js:54:5
    at new Promise (<anonymous>)
    at Object.co (D:\JS\passport\node_modules\co\index.js:50:10)
    at Object.toPromise (D:\JS\passport\node_modules\co\index.js:118:63)
    at next (D:\JS\passport\node_modules\co\index.js:99:29)

pid: 8460
hostname: ghm-pc

2018-01-21 08:35:32,204 ERROR 10704 [-/127.0.0.1/-/181ms POST /login] nodejs.ReferenceError: username is not defined
    at app.passport.verify (D:\JS\passport\app.js:33:31)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

pid: 10704
hostname: ghm-pc

2018-01-21 11:16:40,498 ERROR 16900 [-/127.0.0.1/-/198ms POST /login] nodejs.ReferenceError: existUser is not defined
    at app.passport.verify (D:\JS\passport\app.js:37:9)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

pid: 16900
hostname: ghm-pc

2018-01-21 12:14:09,451 ERROR 444 [-/127.0.0.1/-/26ms GET /login] nodejs.ReferenceError: user is not defined
    at HomeController.login (D:\JS\passport\app\controller\home.js:16:17)
    at callController (D:\JS\passport\node_modules\egg-core\lib\loader\mixin\controller.js:125:18)
    at callController.next (<anonymous>)
    at onFulfilled (D:\JS\passport\node_modules\co\index.js:65:19)
    at D:\JS\passport\node_modules\co\index.js:54:5
    at new Promise (<anonymous>)
    at Object.co (D:\JS\passport\node_modules\co\index.js:50:10)
    at Object.toPromise (D:\JS\passport\node_modules\co\index.js:118:63)
    at next (D:\JS\passport\node_modules\co\index.js:99:29)
    at onFulfilled (D:\JS\passport\node_modules\co\index.js:69:7)
    at D:\JS\passport\node_modules\co\index.js:54:5
    at new Promise (<anonymous>)
    at Object.co (D:\JS\passport\node_modules\co\index.js:50:10)
    at Object.toPromise (D:\JS\passport\node_modules\co\index.js:118:63)
    at next (D:\JS\passport\node_modules\co\index.js:99:29)
    at onFulfilled (D:\JS\passport\node_modules\co\index.js:69:7)

pid: 444
hostname: ghm-pc

2018-01-21 12:18:07,761 ERROR 8964 [-/127.0.0.1/-/17ms GET /login] nodejs.ReferenceError: user is not defined
    at HomeController.login (D:\JS\passport\app\controller\home.js:16:17)
    at callController (D:\JS\passport\node_modules\egg-core\lib\loader\mixin\controller.js:125:18)
    at callController.next (<anonymous>)
    at onFulfilled (D:\JS\passport\node_modules\co\index.js:65:19)
    at D:\JS\passport\node_modules\co\index.js:54:5
    at new Promise (<anonymous>)
    at Object.co (D:\JS\passport\node_modules\co\index.js:50:10)
    at Object.toPromise (D:\JS\passport\node_modules\co\index.js:118:63)
    at next (D:\JS\passport\node_modules\co\index.js:99:29)
    at onFulfilled (D:\JS\passport\node_modules\co\index.js:69:7)
    at D:\JS\passport\node_modules\co\index.js:54:5
    at new Promise (<anonymous>)
    at Object.co (D:\JS\passport\node_modules\co\index.js:50:10)
    at Object.toPromise (D:\JS\passport\node_modules\co\index.js:118:63)
    at next (D:\JS\passport\node_modules\co\index.js:99:29)
    at onFulfilled (D:\JS\passport\node_modules\co\index.js:69:7)

pid: 8964
hostname: ghm-pc

2018-01-21 12:21:57,573 ERROR 10160 [-/127.0.0.1/-/38ms GET /login] nodejs.ReferenceError: user is not defined
    at HomeController.login (D:\JS\passport\app\controller\home.js:19:25)
    at callController (D:\JS\passport\node_modules\egg-core\lib\loader\mixin\controller.js:125:18)
    at callController.next (<anonymous>)
    at onFulfilled (D:\JS\passport\node_modules\co\index.js:65:19)
    at D:\JS\passport\node_modules\co\index.js:54:5
    at new Promise (<anonymous>)
    at Object.co (D:\JS\passport\node_modules\co\index.js:50:10)
    at Object.toPromise (D:\JS\passport\node_modules\co\index.js:118:63)
    at next (D:\JS\passport\node_modules\co\index.js:99:29)
    at onFulfilled (D:\JS\passport\node_modules\co\index.js:69:7)
    at D:\JS\passport\node_modules\co\index.js:54:5
    at new Promise (<anonymous>)
    at Object.co (D:\JS\passport\node_modules\co\index.js:50:10)
    at Object.toPromise (D:\JS\passport\node_modules\co\index.js:118:63)
    at next (D:\JS\passport\node_modules\co\index.js:99:29)
    at onFulfilled (D:\JS\passport\node_modules\co\index.js:69:7)

pid: 10160
hostname: ghm-pc

2018-01-21 12:26:33,595 ERROR 5732 [-/127.0.0.1/-/15ms GET /login] nodejs.ReferenceError: user is not defined
    at HomeController.login (D:\JS\passport\app\controller\home.js:19:25)
    at callController (D:\JS\passport\node_modules\egg-core\lib\loader\mixin\controller.js:125:18)
    at callController.next (<anonymous>)
    at onFulfilled (D:\JS\passport\node_modules\co\index.js:65:19)
    at D:\JS\passport\node_modules\co\index.js:54:5
    at new Promise (<anonymous>)
    at Object.co (D:\JS\passport\node_modules\co\index.js:50:10)
    at Object.toPromise (D:\JS\passport\node_modules\co\index.js:118:63)
    at next (D:\JS\passport\node_modules\co\index.js:99:29)
    at onFulfilled (D:\JS\passport\node_modules\co\index.js:69:7)
    at D:\JS\passport\node_modules\co\index.js:54:5
    at new Promise (<anonymous>)
    at Object.co (D:\JS\passport\node_modules\co\index.js:50:10)
    at Object.toPromise (D:\JS\passport\node_modules\co\index.js:118:63)
    at next (D:\JS\passport\node_modules\co\index.js:99:29)
    at onFulfilled (D:\JS\passport\node_modules\co\index.js:69:7)

pid: 5732
hostname: ghm-pc

2018-01-21 13:19:02,540 ERROR 16740 [-/127.0.0.1/-/19ms GET /login] nodejs.ReferenceError: user is not defined
    at HomeController.login (D:\JS\passport\app\controller\home.js:21:25)
    at callController (D:\JS\passport\node_modules\egg-core\lib\loader\mixin\controller.js:125:18)
    at callController.next (<anonymous>)
    at onFulfilled (D:\JS\passport\node_modules\co\index.js:65:19)
    at D:\JS\passport\node_modules\co\index.js:54:5
    at new Promise (<anonymous>)
    at Object.co (D:\JS\passport\node_modules\co\index.js:50:10)
    at Object.toPromise (D:\JS\passport\node_modules\co\index.js:118:63)
    at next (D:\JS\passport\node_modules\co\index.js:99:29)
    at onFulfilled (D:\JS\passport\node_modules\co\index.js:69:7)
    at D:\JS\passport\node_modules\co\index.js:54:5
    at new Promise (<anonymous>)
    at Object.co (D:\JS\passport\node_modules\co\index.js:50:10)
    at Object.toPromise (D:\JS\passport\node_modules\co\index.js:118:63)
    at next (D:\JS\passport\node_modules\co\index.js:99:29)
    at onFulfilled (D:\JS\passport\node_modules\co\index.js:69:7)

pid: 16740
hostname: ghm-pc

2018-01-21 15:29:33,076 ERROR 1608 [-/::1/-/6ms GET /home] nodejs.ReferenceError: ctx is not defined
    at HomeController.render (D:\JS\passport\app\controller\home.js:73:5)
    at callController (D:\JS\passport\node_modules\egg-core\lib\loader\mixin\controller.js:125:18)
    at callController.next (<anonymous>)
    at onFulfilled (D:\JS\passport\node_modules\co\index.js:65:19)
    at D:\JS\passport\node_modules\co\index.js:54:5
    at new Promise (<anonymous>)
    at Object.co (D:\JS\passport\node_modules\co\index.js:50:10)
    at Object.toPromise (D:\JS\passport\node_modules\co\index.js:118:63)
    at next (D:\JS\passport\node_modules\co\index.js:99:29)
    at onFulfilled (D:\JS\passport\node_modules\co\index.js:69:7)
    at D:\JS\passport\node_modules\co\index.js:54:5
    at new Promise (<anonymous>)
    at Object.co (D:\JS\passport\node_modules\co\index.js:50:10)
    at Object.toPromise (D:\JS\passport\node_modules\co\index.js:118:63)
    at next (D:\JS\passport\node_modules\co\index.js:99:29)
    at onFulfilled (D:\JS\passport\node_modules\co\index.js:69:7)

pid: 1608
hostname: ghm-pc

2018-01-21 15:30:17,366 ERROR 1608 [-/::1/-/4ms GET /home] nodejs.ReferenceError: ctx is not defined
    at HomeController.render (D:\JS\passport\app\controller\home.js:73:5)
    at callController (D:\JS\passport\node_modules\egg-core\lib\loader\mixin\controller.js:125:18)
    at callController.next (<anonymous>)
    at onFulfilled (D:\JS\passport\node_modules\co\index.js:65:19)
    at D:\JS\passport\node_modules\co\index.js:54:5
    at new Promise (<anonymous>)
    at Object.co (D:\JS\passport\node_modules\co\index.js:50:10)
    at Object.toPromise (D:\JS\passport\node_modules\co\index.js:118:63)
    at next (D:\JS\passport\node_modules\co\index.js:99:29)
    at onFulfilled (D:\JS\passport\node_modules\co\index.js:69:7)
    at D:\JS\passport\node_modules\co\index.js:54:5
    at new Promise (<anonymous>)
    at Object.co (D:\JS\passport\node_modules\co\index.js:50:10)
    at Object.toPromise (D:\JS\passport\node_modules\co\index.js:118:63)
    at next (D:\JS\passport\node_modules\co\index.js:99:29)
    at onFulfilled (D:\JS\passport\node_modules\co\index.js:69:7)

pid: 1608
hostname: ghm-pc

2018-01-21 23:05:54,254 ERROR 13796 [-/127.0.0.1/-/68ms GET /rule?] nodejs.ReferenceError: Result is not defined
    at HomeController.user (D:\JS\passport\app\controller\home.js:91:18)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

pid: 13796
hostname: ghm-pc

2018-01-24 14:05:43,201 ERROR 7268 nodejs.MongoError: E11000 duplicate key error collection: test.users index: code_1 dup key: { : null }
    at Function.MongoError.create (E:\JS\passport2\node_modules\mongodb-core\lib\error.js:31:11)
    at E:\JS\passport2\node_modules\mongodb-core\lib\connection\pool.js:497:72
    at authenticateStragglers (E:\JS\passport2\node_modules\mongodb-core\lib\connection\pool.js:443:16)
    at Connection.messageHandler (E:\JS\passport2\node_modules\mongodb-core\lib\connection\pool.js:477:5)
    at Socket.<anonymous> (E:\JS\passport2\node_modules\mongodb-core\lib\connection\connection.js:333:22)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:594:20)
name: 'MongoError'
message: 'E11000 duplicate key error collection: test.users index: code_1 dup key: { : null }'
ok: 0
errmsg: 'E11000 duplicate key error collection: test.users index: code_1 dup key: { : null }'
code: 11000
codeName: 'DuplicateKey'
pid: 7268
hostname: USER-GALVAKJA59

2018-01-24 14:08:28,038 ERROR 8156 nodejs.MongoError: E11000 duplicate key error collection: test.users index: usercode_1 dup key: { : null }
    at Function.MongoError.create (E:\JS\passport2\node_modules\mongodb-core\lib\error.js:31:11)
    at E:\JS\passport2\node_modules\mongodb-core\lib\connection\pool.js:497:72
    at authenticateStragglers (E:\JS\passport2\node_modules\mongodb-core\lib\connection\pool.js:443:16)
    at Connection.messageHandler (E:\JS\passport2\node_modules\mongodb-core\lib\connection\pool.js:477:5)
    at Socket.<anonymous> (E:\JS\passport2\node_modules\mongodb-core\lib\connection\connection.js:333:22)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:594:20)
name: 'MongoError'
message: 'E11000 duplicate key error collection: test.users index: usercode_1 dup key: { : null }'
ok: 0
errmsg: 'E11000 duplicate key error collection: test.users index: usercode_1 dup key: { : null }'
code: 11000
codeName: 'DuplicateKey'
pid: 8156
hostname: USER-GALVAKJA59

2018-01-24 16:29:11,564 ERROR 9584 nodejs.ClusterClientNoResponseError: client no response in 2913037ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (E:\JS\passport2\node_modules\cluster-client\lib\leader.js:73:23)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
name: 'ClusterClientNoResponseError'
pid: 9584
hostname: USER-GALVAKJA59

2018-01-25 08:39:08,721 ERROR 9584 nodejs.ClusterClientNoResponseError: client no response in 55794600ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (E:\JS\passport2\node_modules\cluster-client\lib\leader.js:73:23)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
name: 'ClusterClientNoResponseError'
pid: 9584
hostname: USER-GALVAKJA59

